/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cpabe_CONSTANTS_H
#define cpabe_CONSTANTS_H

#include "cpabe_types.h"



class cpabeConstants {
 public:
  cpabeConstants();

};

extern const cpabeConstants g_cpabe_constants;



#endif
