// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Cpabe.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class CpabeHandler : virtual public CpabeIf {
 public:
  CpabeHandler() {
    // Your initialization goes here
  }

  void getMessage(std::string& _return, const std::string& uid, const std::string& update_time, const std::vector<std::string> & attrs) {
    // Your implementation goes here
    printf("getMessage\n");
  }

  bool setMessage(const std::string& msg) {
    // Your implementation goes here
    printf("setMessage\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CpabeHandler> handler(new CpabeHandler());
  shared_ptr<TProcessor> processor(new CpabeProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

