/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cpabe_constants.h"



const cpabeConstants g_cpabe_constants;

cpabeConstants::cpabeConstants() {
}



